'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { AnimatedButton } from '@/components/ui/AnimatedButton';
import { AnimatedCard } from '@/components/ui/AnimatedCard';
import { HeroSlider } from '@/components/ui/HeroSlider';
import { AutoGeneratedBanner } from '@/components/ui/AutoGeneratedBanner';
import { getAllCreators, getUpcomingEvents } from '@/lib/dataService';
import { Creator, Event } from '@/lib/types';

export default function Home() {
  const [featuredCreators, setFeaturedCreators] = useState<Creator[]>([]);
  const [heroEvents, setHeroEvents] = useState<Event[]>([]);

  useEffect(() => {
    async function fetchData() {
      try {
        const [creators, events] = await Promise.all([
          getAllCreators(),
          getUpcomingEvents()
        ]);
        setFeaturedCreators(creators.slice(0, 6)); // Show first 6 creators
        setHeroEvents(events.slice(0, 3)); // Show first 3 events for hero slider
      } catch (error) {
        console.error('Failed to fetch data:', error);
      }
    }
    
    fetchData();
  }, []);
  return (
    <div className="min-h-screen bg-white">
      <Header />
      
      <main>
        {/* Hero Slider Section */}
        {heroEvents.length > 0 && (
          <HeroSlider events={heroEvents} autoPlay={true} autoPlayDelay={6000} />
        )}
        
        {/* Auto Generated Banners */}
        <section className="py-12 px-4 bg-gray-50">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-8">注目のコンテンツ</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {featuredCreators.slice(0, 3).map((creator, index) => (
                <AutoGeneratedBanner
                  key={creator.id}
                  data={creator}
                  type="creator"
                  style={['minimal', 'vibrant', 'professional'][index % 3] as any}
                  size="medium"
                />
              ))}
            </div>
          </div>
        </section>

        {/* Original Hero Section (now secondary) */}
        <section className="relative bg-gradient-to-br from-blue-50 to-purple-50 py-20 px-4 overflow-hidden">
          <motion.div 
            className="max-w-7xl mx-auto text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <motion.div 
              className="mb-6"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2, duration: 0.5 }}
            >
              <span className="inline-block bg-blue-100 text-blue-800 px-4 py-2 rounded-full text-sm font-medium mb-4">
                🎉 次回イベント開催決定！
              </span>
            </motion.div>
            <motion.h1 
              className="text-4xl md:text-6xl font-bold text-gray-900 mb-6"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3, duration: 0.8 }}
            >
              デザインギルド
            </motion.h1>
            <motion.p 
              className="text-xl md:text-2xl text-gray-600 mb-8 max-w-3xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4, duration: 0.8 }}
            >
              クリエイターとの出会いを創り出す<br />
              デザインコミュニティプラットフォーム
            </motion.p>
            <motion.div 
              className="flex flex-col sm:flex-row gap-4 justify-center"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5, duration: 0.8 }}
            >
              <AnimatedButton size="lg" className="shadow-lg" onClick={() => window.location.href = '/events'}>
                イベントに参加する
              </AnimatedButton>
              <AnimatedButton variant="outline" size="lg" onClick={() => window.location.href = '/creators'}>
                クリエイターを探す
              </AnimatedButton>
            </motion.div>
          </motion.div>
        </section>

        {/* About Section */}
        <section className="py-20 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                デザインギルドとは
              </h2>
              <p className="text-lg text-gray-600 max-w-3xl mx-auto">
                デザインギルドは、才能あるクリエイターと素晴らしいプロジェクトを結ぶプラットフォームです。
                定期的なイベントとネットワーキングを通じて、デザイン業界の未来を一緒に築いていきます。
              </p>
            </div>
            
            <motion.div 
              className="grid md:grid-cols-3 gap-8"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.2 }}
              variants={{
                hidden: { opacity: 0 },
                visible: {
                  opacity: 1,
                  transition: {
                    staggerChildren: 0.2
                  }
                }
              }}
            >
              <motion.div 
                className="text-center"
                variants={{
                  hidden: { opacity: 0, y: 20 },
                  visible: { opacity: 1, y: 0 }
                }}
              >
                <motion.div 
                  className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4"
                  whileHover={{ scale: 1.1, rotate: 5 }}
                  transition={{ type: "spring", stiffness: 400, damping: 10 }}
                >
                  <svg className="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                  </svg>
                </motion.div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">コミュニティ</h3>
                <p className="text-gray-600">
                  同じ志を持つクリエイター同士が繋がり、刺激し合える環境を提供します。
                </p>
              </motion.div>
              
              <motion.div 
                className="text-center"
                variants={{
                  hidden: { opacity: 0, y: 20 },
                  visible: { opacity: 1, y: 0 }
                }}
              >
                <motion.div 
                  className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4"
                  whileHover={{ scale: 1.1, rotate: -5 }}
                  transition={{ type: "spring", stiffness: 400, damping: 10 }}
                >
                  <svg className="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </motion.div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">スキルアップ</h3>
                <p className="text-gray-600">
                  ワークショップや勉強会を通じて、最新のデザイントレンドとスキルを学べます。
                </p>
              </motion.div>
              
              <motion.div 
                className="text-center"
                variants={{
                  hidden: { opacity: 0, y: 20 },
                  visible: { opacity: 1, y: 0 }
                }}
              >
                <motion.div 
                  className="w-16 h-16 bg-amber-100 rounded-full flex items-center justify-center mx-auto mb-4"
                  whileHover={{ scale: 1.1, rotate: 5 }}
                  transition={{ type: "spring", stiffness: 400, damping: 10 }}
                >
                  <svg className="w-8 h-8 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m8 6V9a2 2 0 00-2-2H10a2 2 0 00-2 2v3.1M15 13l-3-3-3 3" />
                  </svg>
                </motion.div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">キャリア</h3>
                <p className="text-gray-600">
                  プロジェクトマッチングや転職支援を通じて、キャリアアップをサポートします。
                </p>
              </motion.div>
            </motion.div>
          </div>
        </section>

        {/* Featured Creators Section */}
        <section className="py-20 px-4 bg-gray-50">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                注目のクリエイター
              </h2>
              <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                デザインギルドで活躍する才能豊かなクリエイターたちをご紹介します。
              </p>
            </div>
            
            <motion.div 
              className="grid md:grid-cols-2 lg:grid-cols-3 gap-8"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.1 }}
              variants={{
                hidden: { opacity: 0 },
                visible: {
                  opacity: 1,
                  transition: {
                    staggerChildren: 0.1
                  }
                }
              }}
            >
              {featuredCreators.map((creator) => (
                <motion.div
                  key={creator.id}
                  variants={{
                    hidden: { opacity: 0, y: 20 },
                    visible: { opacity: 1, y: 0 }
                  }}
                >
                  <AnimatedCard
                    id={creator.id}
                    name={creator.name}
                    profession={creator.profession}
                    skills={creator.skills}
                    onClick={(id) => {
                      window.location.href = `/creators/${id}`;
                    }}
                  />
                </motion.div>
              ))}
            </motion.div>
          </div>
        </section>

        {/* Next Event Section */}
        <section className="py-20 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 md:p-12 text-white">
              <div className="grid md:grid-cols-2 gap-8 items-center">
                <div>
                  <h2 className="text-3xl md:text-4xl font-bold mb-4">
                    次回イベント
                  </h2>
                  <h3 className="text-xl md:text-2xl mb-4">
                    クリエイティブ・ネットワーキング 2024
                  </h3>
                  <p className="text-blue-100 mb-6">
                    デザイン業界のトレンドセッションと交流会を開催。
                    新しい出会いとインスピレーションを見つけませんか？
                  </p>
                  <div className="space-y-2 mb-6">
                    <p className="flex items-center">
                      <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                      </svg>
                      2024年7月15日（土）14:00-18:00
                    </p>
                    <p className="flex items-center">
                      <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                      東京・渋谷クリエイティブセンター
                    </p>
                  </div>
                  <AnimatedButton variant="secondary" size="lg" onClick={() => window.location.href = '/events/1'}>
                    詳細を見る
                  </AnimatedButton>
                </div>
                <div className="relative">
                  <div className="bg-white/10 backdrop-blur-sm rounded-lg p-6">
                    <h4 className="text-lg font-semibold mb-4">参加者特典</h4>
                    <ul className="space-y-2 text-blue-100">
                      <li className="flex items-center">
                        <svg className="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        業界著名人による講演
                      </li>
                      <li className="flex items-center">
                        <svg className="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        ポートフォリオレビュー
                      </li>
                      <li className="flex items-center">
                        <svg className="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                        交流会・ドリンク付き
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Contact/Signup CTA Section */}
        <section className="py-20 px-4 bg-gray-900">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              デザインギルドに参加しませんか？
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              クリエイターとしてのキャリアを次のレベルへ。
              今すぐコミュニティに参加して、新しい可能性を発見しましょう。
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <AnimatedButton variant="primary" size="lg" className="bg-blue-600 hover:bg-blue-700" onClick={() => window.location.href = '/events'}>
                今すぐ参加する
              </AnimatedButton>
              <AnimatedButton variant="outline" size="lg" className="border-gray-300 text-gray-300 hover:bg-gray-800" onClick={() => window.location.href = '/events'}>
                詳細を見る
              </AnimatedButton>
            </div>
            <p className="text-sm text-gray-400 mt-6">
              完全無料 • オープンコミュニティ • 気軽な参加
            </p>
          </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
}